### ISSUE TITLE
Rethink Vaults & Strategies list

### ISSUE THREAD

**Issue by lehnberg** [yearn/yearn-docs#285]
https://github.com/yearn/yearn-docs/pull/278 got me thinking how inefficient and error-prone a manually administered list of  vaults and strategies is to have in our docs repo: https://docs.yearn.finance/yearn-finance/yvaults/vaults-and-strategies

This will suffer and struggle to be kept up to date, as new vaults and strategies are added on a constant basis.
Meanwhile, we have a vault registry at v2.registry.ychad.eth that lists all vaults, and we have a fantastic resource that combines all this with strategies and their allocations at: https://yearn-hub.vercel.app

Our documentation should never replicate information that's readily available elsewhere, we should strive to work by the principle of keeping a single source of truth for all our data. So rather than manually tending to a list, perhaps we should just link to https://yearn-hub.vercel.app and/or the registry with some descriptive information?

**Comment by philburrrt** [comment]
My idea was to have something like this: 

## StrategyLenderYieldOptimiser
**Contract**: [0x6a97FC93e39b3f792f1fD6e01565ff412B002D20](https://etherscan.io/address/0x6a97FC93e39b3f792f1fD6e01565ff412B002D20#code)
**Description**: Lends TOKEN on a lending protocol to gain interest and accumulate staked AAVE as rewards. When the staked AAVE unlocks the AAVE will be harvested, sold for more TOKEN, and re-deposited into the vault.
Diagram: (jpg of strat diagram)

The diagram would be value added now but not when v3 comes out. When v3 does release, the page will mostly be irrelevant. 

Maybe it's a better use of Docs team's time to keep up with descriptions/diagrams in the metadata repo, since that's where all user facing things will be pulled from in the future.

**Comment by lehnberg** [comment]
Yes, it sounds like that might duplicate a lot of the content in metadata. 

If we keep all this data in one place, we could programmatically build documentation that gets updated as changes to metadata are made. 

Keeping the principle of a single source of truth intact.

**Comment by lehnberg** [comment]
Fixed by #304
